# Grunt aliases
---
# Create a zipped artifact from a fresh build
'artifact':
  - 'update-version'
  - 'clean:artifact'
  - 'clean:artifact-zip'
  - 'clean:vendor'
  - 'shell:composerProduction'
  - 'copy:artifact'
  - 'compress:artifact'
  - 'shell:composerInstall'

# Create a zipped artifact from and do not keep the artifact folder
'artifact:zip':
  - 'artifact'
  - 'clean:artifact'

'deploy:trunk':
  - 'update-version'
  - 'create:artifact'
  - 'wp_deploy:trunk'

'deploy:master':
  - 'update-version-release'
  - 'create:artifact'
  - 'wp_deploy:master'
